ngneat/hot-toast

CHANGELOG.md, README.md, projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.html, projects/ngneat/hot-toast/src/lib/components/indicator/icons/checkmark/checkmark.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/icons/error/error.component.scss, projects/ngneat/hot-toast/src/lib/hot-toast.module.ts
[x] Bugfix
[ ] Feature
Issue Number: #11 #13 
[ ] Yes
[x] No
=> Development - Fixes #13, #11

src/app/sections/example/example.component.ts
✅ Closes: #9
Issue Number: #9 
```
[ ] Yes
[x] No
```
=> docs: ✏️ fix examples link

src/app/app.component.html
The link routing to react host toast has been updated to point to the proper website.
```
[ ] Bugfix
[ ] Feature
```
The link in the Landing page which points to `React Hot Toast` is broken.
The link mentioned in the landing page now points correctly to the `React Hot Toast` website.
```
[ ] Yes
[x] No
```
=> docs: broken link to react-hot-toast fix

.github/workflows/release-beta.yaml, .github/workflows/release.yaml
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
Github actions are failing.
Fix Github actions.
```
[ ] Yes
[x] No
```
=> ci: 🎡 github actions workflow file syntax correction

projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.html, projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.scss
✅ Closes: #21
```
[x] Bugfix
[ ] Feature
```
Issue Number: #21 
```
[ ] Yes
[x] No
```
=> fix: 🐛 prepend theme class with 'hot-toast-theme-', closes #21

projects/ngneat/hot-toast/schematics/ng-add/index.ts, projects/ngneat/hot-toast/schematics/ng-add/utils/index.ts
✅ Closes: #25
```
[x] Bugfix
[ ] Feature
```
Issue Number: #25 
```
[ ] Yes
[x] No
```
=> fix: 🐛 schematics: create getWorkSpace function in utility

.github/workflows/release-beta.yaml, .releaserc.json
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
Issue Number: #27 
```
[ ] Yes
[x] No
```
=> Create GitHub Release

projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.scss
✅ Closes: #33
```
[x] Bugfix
[ ] Feature
```
Issue Number: #33 
```
[ ] Yes
[x] No
```
=> fix: 🐛 icon and close button alignment in cross browser

projects/ngneat/hot-toast/src/lib/hot-toast.service.ts
✅ Closes: #35
```
[x] Bugfix
[ ] Feature
```
Issue Number: #35 
```
[ ] Yes
[x] No
```
=> fix: 🐛 block rendering for SSR

projects/ngneat/hot-toast/src/lib/hot-toast.service.ts
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Remove redundant checks for server.
```
[ ] Yes
[x] No
```
=> refactor: 💡 remove redundant checks

CHANGELOG.md, projects/ngneat/hot-toast/src/lib/components/hot-toast-container/hot-toast-container.component.html, projects/ngneat/hot-toast/src/lib/components/hot-toast-container/hot-toast-container.component.scss, projects/ngneat/hot-toast/src/lib/components/hot-toast-container/hot-toast-container.component.ts, projects/ngneat/hot-toast/src/lib/hot-toast.service.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #38 
```
[ ] Yes
[x] No
```
=> Wait until application is stable (Closes #38)

projects/ngneat/hot-toast/src/lib/hot-toast.module.ts, projects/ngneat/hot-toast/src/lib/hot-toast.service.ts, src/app/app.component.ts, src/app/sections/example/example.component.ts, tsconfig.json
✅ Closes #38
```
[x] Bugfix
[ ] Feature
```
Issue Number: #38 
```
[ ] Yes
[x] No
```
=> fix(hot-toast): initialize only when toast called first time

README.md, cypress/integration/toast_html.spec.ts, cypress/integration/toast_injector.spec.ts, cypress/integration/toast_template_context.spec.ts, projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.html, projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts, projects/ngneat/hot-toast/src/lib/hot-toast.model.ts, src/app/app.module.ts, src/app/sections/example/example.component.html, src/app/sections/example/example.component.ts, src/app/shared/components/emoji-button/emoji-button.component.html, src/app/shared/components/emoji-button/emoji-button.component.scss, src/app/shared/components/emoji-button/emoji-button.component.ts
#49
```
[ ] Bugfix
[x] Feature
```
Issue Number: #49
```
[ ] Yes
[x] No
```
=> feat(hot-toast): add support for context and injector

cypress/integration/toast_data.spec.ts, cypress/integration/toast_template_data.spec.ts, projects/ngneat/hot-toast/src/lib/components/hot-toast-container/hot-toast-container.component.ts, projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.html, projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.ts, projects/ngneat/hot-toast/src/lib/hot-toast-ref.ts, projects/ngneat/hot-toast/src/lib/hot-toast.model.ts, projects/ngneat/hot-toast/src/lib/hot-toast.service.ts, projects/ngneat/hot-toast/src/public-api.ts, src/app/app.module.ts, src/app/sections/example/example.component.html, src/app/sections/example/example.component.ts
#54
```
[ ] Bugfix
[x] Feature
```
Issue Number: #54 
```
[ ] Yes
[x] No
```
=> feat(hot-toast): add an option to pass data with component

projects/ngneat/hot-toast/src/lib/hot-toast.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(service): add protection in close method

README.md, package-lock.json
fix #61
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #61 
```
[ ] Yes
[x] No
```
=> docs(readme.md): use v1 of @ngneat/overview

CHANGELOG.md, projects/ngneat/hot-toast/src/lib/components/hot-toast-container/hot-toast-container.component.ts, projects/ngneat/hot-toast/src/lib/hot-toast.model.ts, projects/ngneat/hot-toast/src/lib/hot-toast.service.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #66 
If id is not provided, all the toasts will be closed through `HotToastService.close`.
```
[ ] Yes
[x] No
```
=> Feature request: Clear all opened toaster #66

CHANGELOG.md, package-lock.json, package.json, projects/ngneat/hot-toast/src/lib/components/animated-icon/animated-icon.component.scss, projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/icons/checkmark/checkmark.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/icons/error/error.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/icons/loader/loader.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/icons/warning/warning.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/indicator.component.scss
```
[ ] Bugfix
[x] Feature
```
To override styles, user have to use `!important` keyword in css.
To override styles, user can use the custom CSS properties, e.g. `--hot-toast-bg: red`.
```
[ ] Yes
[x] No
```
=> feat: add custom properties / variables for all css styles for easy overriding

package-lock.json, projects/ngneat/hot-toast/package.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Supported versions of angular are 8+, which is incorrect.
Supported versions of angular are 9+.
```
[ ] Yes
[x] No
```
=> build(package.json): change angular supported versions

.stylelintrc.json, .vscode/settings.json, CHANGELOG.md, package-lock.json, package.json, projects/ngneat/hot-toast/src/lib/components/animated-icon/animated-icon.component.scss, projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/icons/checkmark/checkmark.component.html, projects/ngneat/hot-toast/src/lib/components/indicator/icons/checkmark/checkmark.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/icons/error/error.component.html, projects/ngneat/hot-toast/src/lib/components/indicator/icons/error/error.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/icons/info/info.component.html, projects/ngneat/hot-toast/src/lib/components/indicator/icons/info/info.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/icons/loader/loader.component.html, projects/ngneat/hot-toast/src/lib/components/indicator/icons/loader/loader.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/icons/warning/warning.component.html, projects/ngneat/hot-toast/src/lib/components/indicator/icons/warning/warning.component.scss, projects/ngneat/hot-toast/src/lib/components/indicator/indicator.component.scss
```
[x] Bugfix
[ ] Feature
```
Issue Number: #81 #84 
Issues fixed
```
[ ] Yes
[x] No
```
=> Fix CSS issues

README.md
add docuentation with the steps to add styles when using version 5 (Angular 15>=)
113
```
[ ] Bugfix
[ ] Feature
```
REAME is missing the description of how to add styles when using version 5
README now includes a description on how to add styles to your project.
```
[ ] Yes
[x] No
```
=> docs(readme.md): update styles reference for version 5

README.md, cypress/e2e/toast-for-feature.cy.ts, projects/ngneat/hot-toast/src/lib/hot-toast.module.ts, projects/ngneat/hot-toast/src/lib/hot-toast.service.ts, src/app/app.component.html, src/app/app.module.ts, src/app/sections/for-feature/for-feature.component.html, src/app/sections/for-feature/for-feature.component.ts, src/app/sections/for-feature/for-feature.module.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #104 
Allow to setup hot-toast for dedicated with dedicated configuration
```
[ ] Yes
[x] No
```
=> feat: add forFeature configuration

projects/ngneat/hot-toast/src/lib/components/hot-toast/hot-toast.component.html
fix #124
```
[x] Bugfix
[ ] Feature
```
Issue Number: #124 
Fixes #124 
```
[ ] Yes
[x] No
```
=> fix(hot-toast.component.html): usage of dynamicView directive
